# Generated by Django 4.2.7 on 2025-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("automation", "Automation Request"),
                    ("bug_report", "Bug Report"),
                    ("feature_request", "Feature Request"),
                    ("maintenance", "Maintenance"),
                    ("wfm_requests", "WFM requests"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
